version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  allow:
  - dependency-type: direct
  - dependency-type: indirect
  ignore:
  - dependency-name: aws-partitions
    versions:
    - 1.426.0
    - 1.437.0
  - dependency-name: activesupport
    versions:
    - 6.1.3
    - 6.1.3.1
  - dependency-name: aws-sdk-core
    versions:
    - 3.112.0
    - 3.113.0
  - dependency-name: aws-eventstream
    versions:
    - 1.1.1
  - dependency-name: activemodel
    versions:
    - 6.1.2
    - 6.1.2.1
