inherit_from:
  - .rubocop_todo.yml
  - https://raw.githubusercontent.com/GetTerminus/ruby_shared_configs/master/.rubocop-3-1.yml



AllCops:
  Exclude:
    - bin/*
    - spec/**/*.rb
    - vendor/**/*

Style/Documentation:
  Enabled: false

Style/TrailingCommaInArguments:
  Enabled: false

Metrics/LineLength:
  Exclude:
    - 'lib/protobufs/**/*.rb'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*_spec.rb'
