name: 'Test'

on: push

jobs:
  run-tests:
    name: Test code
    strategy:
      fail-fast: false
      matrix:
        rubyVersion: ["2.7.6", "3.0.4", "3.1.2"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.rubyVersion }}
          bundler-cache: true
          cache-version: "${{ matrix.rubyVersion }}-1"
      - name: Run RSpec
        run: bundle exec rspec
      - name: Coveralls
        uses: coverallsapp/github-action@v1.1.2
        continue-on-error: true
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
